language: haskell
notifications:
  email: false
install:
  - cabal install --only-dependencies --enable-tests --force-reinstalls
before_script:
  - cabal configure -fbuildExamples
  - cabal sdist
  - cd ..
  - tar -xf threepenny-gui/dist/threepenny-gui*.tar.gz
  - cd threepenny-gui*
script:
  - cabal configure -fbuildExamples --enable-tests && cabal build && cabal test
